-- SELECT 멸종위기의 대장균 찾기

WITH RECURSIVE Generation_CTE AS (
    SELECT
        ID,
        1 AS GENERATION
    FROM
        ECOLI_DATA
    WHERE
        PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        E.ID,
        G.GENERATION + 1 AS GENERATION
    FROM
        ECOLI_DATA E
    INNER JOIN
        Generation_CTE G
    ON
        E.PARENT_ID = G.ID
)
SELECT
    COUNT(G.ID) AS COUNT,
    G.GENERATION
FROM
    Generation_CTE G
LEFT JOIN
    ECOLI_DATA E ON G.ID = E.PARENT_ID
WHERE
    E.ID IS NULL
GROUP BY
    G.GENERATION
ORDER BY
    G.GENERATION;
